"""Small read-only catalog helpers for the control-center APIs (Plan §P4).

These back ``GET /api/models`` and ``GET /api/configs`` — they project the
on-disk ``configs/models.yaml`` and ``configs/config-*.yaml`` files into the flat
shapes the SPA's ``MODELS`` / ``CONFIGS`` exports consume. Pure reads, no caching,
no state: the files are the source of truth and re-read on each call.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from src.config import (
    CONFIGS_DIR,
    _load_models_registry,
    model_default_level,
    model_thinking_levels,
)


RELEASE_DATES_PATH = CONFIGS_DIR / "model_release_dates.json"


def _load_release_dates(path: Path | None = None) -> dict[str, str]:
    """``{model: "YYYY-MM-DD"}`` from the generated cache; ``{}`` if absent.

    Deliberately forgiving: a missing or corrupt file costs the picker its
    release-date ordering, which is a degraded sort, not a broken dialog. The
    file is generated by ``scripts/sync_model_release_dates.py``.
    """
    target = Path(path) if path is not None else RELEASE_DATES_PATH
    try:
        data = json.loads(target.read_text())
    except (OSError, ValueError):
        return {}
    released = data.get("released")
    if not isinstance(released, dict):
        return {}
    return {k: v for k, v in released.items() if isinstance(v, str)}


def _observed_pair(observed_raw: Any) -> dict[str, Any] | None:
    """``{avg_turn_cost_usd, avg_turn_latency_s}`` when both are present, else None."""
    if isinstance(observed_raw, dict):
        cost = observed_raw.get("avg_turn_cost_usd")
        latency = observed_raw.get("avg_turn_latency_s")
        if cost is not None and latency is not None:
            return {"avg_turn_cost_usd": cost, "avg_turn_latency_s": latency}
    return None


def list_models() -> list[dict[str, Any]]:
    """Project the collapsed ``models.yaml`` into the picker shape (one row/model).

    Each row carries the model name, its OpenRouter id, ``reasoning_type``, the
    ordered ``levels`` (each with its own ``observed`` telemetry), and the
    ``default_level`` (highest). The run identity submitted by the picker is
    ``model(level)`` — so each level is still benchmarked separately — except for
    ``reasoning_type: none`` models (e.g. grok-4.3) which have no levels and submit
    the bare model name. ``observed`` at the top level mirrors the default level so
    the picker can show a headline cost/latency.

    ``retired: true`` entries are OMITTED. Retirement is a *catalog* state, not a
    deletion: a model reaches it when it stops being something you would start a
    new run with, while a frozen config, a saved run config or a placeholder
    somewhere still names it — so ``load_config`` must keep resolving it (and it
    does; nothing in ``src.config`` consults this flag) or those artefacts break.
    The two readers are answering different questions, which is why the filter
    lives here and not in the registry loader: this function is "what may I pick
    NOW", ``_load_models_registry`` is "what does this name mean". Filtering in
    the loader instead would make an old run's model unresolvable, which is the
    failure retirement exists to avoid.
    """
    registry = _load_models_registry()
    release_dates = _load_release_dates()
    out: list[dict[str, Any]] = []
    for base in sorted(registry):
        entry = registry.get(base)
        if not isinstance(entry, dict):
            continue
        # Retired: still resolvable by name, no longer offered as a new choice.
        if entry.get("retired"):
            continue
        observed_map = entry.get("observed") or {}
        levels = model_thinking_levels(entry)
        level_rows = [
            {"level": lvl, "observed": _observed_pair(observed_map.get(lvl))}
            for lvl in levels
        ]
        default_level = model_default_level(entry)
        # Headline observed = the default level's, or the lone "_" block (type none).
        if level_rows:
            headline = level_rows[0]["observed"]
        else:
            headline = _observed_pair(observed_map.get("_"))
        out.append(
            {
                "model": base,
                "openrouter_id": entry.get("openrouter_id"),
                "reasoning_type": entry.get("reasoning_type", "none"),
                "default_level": default_level,
                "levels": level_rows,
                "observed": headline,
                # Vision capability. The benchmark sends screenshots, so the
                # PLAYER must be multimodal; the picker uses this to gate Player
                # choices. Defaults True (every model currently in the registry is
                # vision-capable) — set ``multimodal: false`` on a text-only entry
                # to exclude it from the Player picker.
                "multimodal": bool(entry.get("multimodal", True)),
                # ``YYYY-MM-DD`` or None. Generated from OpenRouter's catalog by
                # scripts/sync_model_release_dates.py, not stored in models.yaml
                # — see that script for why. The picker sorts newest-first on it,
                # and None sorts last rather than being guessed at.
                "released": release_dates.get(base),
            }
        )
    return out


_CONFIG_STEM_RE = re.compile(r"^(config-\d+\.\d+)\.yaml$")


def list_configs(configs_dir: Path | None = None) -> list[str]:
    """Casual config stems discovered from ``configs/config-*.yaml`` (e.g. ``config-3.13``).

    Sorted by version (major, minor) so the dialog shows them in a stable order.
    ``configs_dir`` is injectable for tests; defaults to the repo ``configs/``.
    """
    base = Path(configs_dir) if configs_dir is not None else CONFIGS_DIR
    if not base.exists():
        return []
    stems: list[tuple[tuple[int, int], str]] = []
    for path in base.glob("config-*.yaml"):
        m = _CONFIG_STEM_RE.match(path.name)
        if not m:
            continue
        stem = m.group(1)
        major, minor = stem.split("config-")[1].split(".")
        stems.append(((int(major), int(minor)), stem))
    stems.sort(key=lambda t: t[0])
    # API callers (and ``_validate_config_stem``) use the LAST item as the
    # default. That is the whole rule: highest ``config-X.Y`` wins. The append
    # harness used to be the non-numeric ``config-append`` and was force-fed to
    # the FRONT of this list so it could be selected without ever becoming the
    # default; it is now ``config-5.0``, so it wins the ordinary rule and the
    # special case is gone. Nothing here knows which harness a stem selects.
    return [stem for _, stem in stems]


# The ladder the stop-at catalog is read from. Deliberately the FULL ladder:
# every other benchmark's ladder (easy, first-badge) is a literal prefix of it,
# so this one file is a superset of every story event the referee can detect —
# one catalog, no union step. It happens to be the same file as
# ``executor.OFFICIAL_LADDER`` but is a SEPARATE constant on purpose: that one
# names the legacy full benchmark, this one names "the longest ladder we have".
# A test asserts the superset property so adding a benchmark can't silently
# leave events out of the picker.
STOP_EVENT_LADDER = "configs/checkpoints-firered-v1.yaml"


def list_stop_events(ladder: str | Path | None = None) -> list[dict[str, Any]]:
    """Story events a casual run can be told to stop at — ``[{id, name, type}]``.

    The flattened gate list in ladder order (multigate members expanded in
    place, so ``cascade_badge`` and ``bills_errand_reached`` are each selectable
    on their own rather than only as their any-order group). Deadlines are
    deliberately NOT projected: a casual run runs the ladder observe-only, so a
    gate's turn limit means nothing to it and showing one would imply otherwise.

    Backs ``GET /api/checkpoints`` and validates ``--stop-at`` / the dialog's
    picker. Pure read, no caching — the ladder file is the source of truth.
    """
    from src.referee.checkpoints import load_ladder

    target = Path(ladder) if ladder is not None else Path(STOP_EVENT_LADDER)
    return [
        {"id": cp.id, "name": cp.name, "type": cp.type}
        for cp in load_ladder(target).checkpoints
    ]


def validate_stop_event(
    stop_at: Any, ladder: str | Path | None = None
) -> str | None:
    """Return a known stop-event id, or ``None`` for "no stop event".

    ``None`` and ``""`` both mean unset (the dialog's "—" option posts an empty
    string). Anything else must name a gate in the ladder, else ``ValueError``
    — a typo'd id has to fail at the door, because the alternative is a run that
    quietly never stops early and only reveals the mistake at its turn cap.
    """
    if stop_at is None or stop_at == "":
        return None
    if not isinstance(stop_at, str):
        raise ValueError(f"stop_at must be a string event id, got {stop_at!r}")
    known = [e["id"] for e in list_stop_events(ladder)]
    if stop_at not in known:
        raise ValueError(
            f"unknown stop event {stop_at!r}; known: {', '.join(known)}"
        )
    return stop_at


def stop_at_referee_config(stop_at: str | None) -> dict[str, Any] | None:
    """The ``referee`` config block that makes a run stop at ``stop_at``.

    ``None`` in → ``None`` out (no block; the run has no referee at all, which
    is what a casual run has always had). The single builder for this block:
    both the queue executor and ``pokemon run --stop-at`` call it, so the two
    entry points cannot drift into wiring the run differently.

    ``enforce: False`` is the load-bearing field. The full ladder carries turn
    deadlines, and arming them would let a *pace* gate kill a casual run long
    before it reaches the event you asked for. Observe-only means the only two
    ends are the event and the turn cap.
    """
    if not stop_at:
        return None
    return {
        "checkpoints": STOP_EVENT_LADDER,
        "enforce": False,
        "stop_at": stop_at,
    }


# ---------------------------------------------------------------------------
# Provider profiles + per-config harness facts (backs ``GET /api/profiles``).
#
# The dialog needs two things config-5.0 introduced and nothing served: WHICH
# configs are profile-aware (so it knows when the profile owns the thinking
# ladder) and, per model, the profile's own contract — the legal reasoning
# levels, its default, the endpoint it was probed on, its cache mode, and the
# named variants that apply to it.
#
# Kept here rather than in ``src.agent.provider_profiles`` because these are
# CATALOG reads — "what may I pick now" — and the resolver answers a different
# question: "what does this config mean once bound to a model". The resolver
# needs a config; the picker has none yet.
# ---------------------------------------------------------------------------

APPEND_AGENT_TYPE = "append_compact"


def _config_agent_facts(path: Path) -> dict[str, Any]:
    """``{agent_type, compaction_interval}`` for one config file. Raw read.

    Deliberately NOT ``load_config``: that requires a model alias to resolve, runs
    the whole validator, and would make listing the configs fail because ONE of
    them is broken. This only needs two authored values, so it reads the YAML.

    Both keys may be authored either inside the optional ``player_agent:`` block
    (the config-4.0+ layout) or flat at the top level (config-1.x..3.12), which
    is exactly what ``src.config._hoist_player_agent`` normalises at load time —
    so both places are checked here, block first, mirroring the hoist.
    """
    import yaml

    try:
        raw = yaml.safe_load(path.read_text())
    except (OSError, ValueError):
        return {"agent_type": None, "compaction_interval": None}
    if not isinstance(raw, dict):
        return {"agent_type": None, "compaction_interval": None}
    block = raw.get("player_agent")
    block = block if isinstance(block, dict) else {}

    def _pick(key):
        return block[key] if key in block else raw.get(key)

    agent_type = _pick("agent_type")
    compaction = _pick("compaction")
    every = compaction.get("every_n_turns") if isinstance(compaction, dict) else None
    if not isinstance(every, int) or isinstance(every, bool) or every <= 0:
        every = None
    return {
        "agent_type": agent_type if isinstance(agent_type, str) else None,
        "compaction_interval": every,
    }


def list_config_facts(configs_dir: Path | None = None) -> list[dict[str, Any]]:
    """``[{stem, agent_type, profile_aware, compaction_interval}]`` per casual config.

    Same order (and same membership) as :func:`list_configs` — the LAST entry is
    the default. ``profile_aware`` is the one flag the dialog branches on: an
    ``append_compact`` config resolves a provider profile, so the profile owns
    the legal thinking levels and the endpoint; a legacy config ignores profiles
    entirely (``resolve_provider_profile`` returns before reading the catalog),
    so its dialog must keep offering the full registry ladder.

    Keyed on the config's ``agent_type``, never on its stem: "config-5.x" is
    today's answer, not the rule, and a hand-passed config path has no stem to
    match.
    """
    base = Path(configs_dir) if configs_dir is not None else CONFIGS_DIR
    out: list[dict[str, Any]] = []
    for stem in list_configs(base):
        facts = _config_agent_facts(base / f"{stem}.yaml")
        out.append(
            {
                "stem": stem,
                "agent_type": facts["agent_type"],
                "profile_aware": facts["agent_type"] == APPEND_AGENT_TYPE,
                "compaction_interval": facts["compaction_interval"],
            }
        )
    return out


def load_profile_catalog(path: Path | None = None) -> dict[str, Any]:
    """The raw ``configs/provider-profiles.yaml`` mapping; ``{}`` when unreadable.

    Forgiving like :func:`_load_release_dates`: a missing catalog costs the
    dialog its Advanced panel and its level filter (it falls back to the full
    registry ladder, which is what a legacy config gets), not the dialog.
    """
    import yaml

    from src.agent.provider_profiles import PROFILE_PATH

    target = Path(path) if path is not None else PROFILE_PATH
    try:
        data = yaml.safe_load(target.read_text())
    except (OSError, ValueError):
        return {}
    return data if isinstance(data, dict) else {}


def list_provider_profiles(
    profile_path: Path | None = None, configs_dir: Path | None = None
) -> dict[str, Any]:
    """The append harness's transport contract per pickable model, + config facts.

    ``profiles`` has one row per row of :func:`list_models` — so a retired
    registry entry is absent here too, and a model with no profile entry still
    gets a row (``unprofiled: true``, empty ``reasoning_efforts``) rather than
    vanishing: it IS startable on an append config, it just runs on the
    ``defaults:`` block with no pinned endpoint.

    ``reasoning_efforts`` is the PROBED legal set for that one endpoint, and the
    empty list means "not probed" — the same meaning it has in
    ``resolve_provider_profile``, which waves an empty list through rather than
    rejecting every effort. A caller intersecting a registry ladder with this
    list must therefore treat empty as "no constraint", not as "nothing legal".

    ``variants`` names the profile catalog's named variants whose ``model``
    matches this row — the gemma-guidance / gemma-replay family. They were
    reachable only from ``pokemon run --provider-profile`` until the queue grew
    a profile axis.
    """
    catalog = load_profile_catalog(profile_path)
    profiles = catalog.get("profiles") or {}
    defaults = catalog.get("defaults") or {}
    variants = catalog.get("variants") or {}
    by_model: dict[str, list[str]] = {}
    for name, spec in sorted(variants.items()):
        if isinstance(spec, dict) and isinstance(spec.get("model"), str):
            by_model.setdefault(spec["model"], []).append(name)

    rows: list[dict[str, Any]] = []
    for row in list_models():
        orid = row.get("openrouter_id")
        entry = profiles.get(orid) if isinstance(profiles, dict) else None
        unprofiled = not isinstance(entry, dict)
        merged = {**defaults, **(entry if isinstance(entry, dict) else {})}
        rows.append(
            {
                "model": row["model"],
                "openrouter_id": orid,
                "unprofiled": unprofiled,
                # "" = unpinned, which is what an unprofiled model gets: a
                # default cannot invent an endpoint nobody probed.
                "endpoint": "" if unprofiled else (merged.get("endpoint") or ""),
                "reasoning_efforts": list(merged.get("reasoning_efforts") or []),
                "reasoning_default": merged.get("reasoning_default") or {},
                "final_turn_text_only": bool(merged.get("final_turn_text_only", False)),
                "cache_mode": merged.get("cache_mode") or "unknown",
                "variants": by_model.get(orid, []),
            }
        )
    return {
        "version": catalog.get("version"),
        "reviewed": catalog.get("reviewed"),
        "profiles": rows,
        "configs": list_config_facts(configs_dir),
    }
