"""Refresh `configs/model_release_dates.json` from OpenRouter.

Usage:
    python scripts/sync_model_release_dates.py [--check]

The model picker orders by release date, and the registry has no such field —
`observed.<tier>.last_updated` is when WE last benchmarked a tier, which is a
different thing and is absent entirely for the models nobody has run yet.

OpenRouter's public catalog carries a `created` timestamp per model, and every
registry entry already stores its `openrouter_id`, so the dates are derivable
rather than hand-curated. They land in a separate JSON file instead of inside
models.yaml deliberately: models.yaml is hand-maintained config, this is
generated data, and mixing the two would mean a sync run produces a diff on a
file people edit by hand.

The generated file is committed, so the picker keeps working offline; this
script only needs re-running when models are added to the registry.

`--check` exits 1 if the file is stale (missing or extra models), for use as a
guard without writing anything.
"""
from __future__ import annotations

import argparse
import datetime as _dt
import json
import sys
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.config import _load_models_registry  # noqa: E402

OPENROUTER_CATALOG = "https://openrouter.ai/api/v1/models"
OUT_PATH = Path(__file__).resolve().parents[1] / "configs" / "model_release_dates.json"


def fetch_openrouter_created() -> dict[str, int]:
    """`{openrouter_id: created_unix}` for the whole public catalog."""
    with urllib.request.urlopen(OPENROUTER_CATALOG, timeout=30) as resp:
        payload = json.load(resp)
    out = {}
    for entry in payload.get("data", []):
        mid, created = entry.get("id"), entry.get("created")
        if mid and isinstance(created, (int, float)):
            out[mid] = int(created)
    return out


def build() -> tuple[dict[str, str], list[str]]:
    """`({model: YYYY-MM-DD}, unmatched_models)`."""
    registry = _load_models_registry()
    created = fetch_openrouter_created()
    dates: dict[str, str] = {}
    unmatched: list[str] = []
    for base in sorted(registry):
        entry = registry.get(base)
        if not isinstance(entry, dict):
            continue
        ts = created.get(entry.get("openrouter_id"))
        if ts is None:
            # Never guess a date — an invented one would sort the picker wrongly
            # and look authoritative doing it. Omitted models sort last instead.
            unmatched.append(base)
            continue
        dates[base] = _dt.date.fromtimestamp(ts).isoformat()
    return dates, unmatched


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="report staleness, write nothing")
    args = ap.parse_args()

    dates, unmatched = build()
    for name in unmatched:
        print(f"  WARN no OpenRouter match, release date omitted: {name}", file=sys.stderr)

    existing = {}
    if OUT_PATH.exists():
        existing = json.loads(OUT_PATH.read_text()).get("released", {})

    if args.check:
        added = sorted(set(dates) - set(existing))
        removed = sorted(set(existing) - set(dates))
        changed = sorted(k for k in set(dates) & set(existing) if dates[k] != existing[k])
        if added or removed or changed:
            print(f"STALE — added={added} removed={removed} changed={changed}")
            return 1
        print(f"up to date ({len(dates)} models)")
        return 0

    OUT_PATH.write_text(
        json.dumps(
            {
                "_comment": (
                    "GENERATED by scripts/sync_model_release_dates.py from OpenRouter's "
                    "public catalog `created` field. Do not hand-edit — re-run the script."
                ),
                "released": dates,
            },
            indent=2,
            sort_keys=True,
        )
        + "\n"
    )
    print(f"wrote {OUT_PATH.relative_to(Path.cwd())} — {len(dates)} models, {len(unmatched)} unmatched")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
